name: Say hello with private action

on: [push]

jobs:
  hello_world_job_with_private_action:
    runs-on: ubuntu-latest
    name: A job to say hello with private action
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          who-to-greet: 'My private GitHub Action'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"